# Site settings
title: Merkulova Isabel
description: Model Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Merkulova Isabel
user_description: 
email: @gmail.com
